var machineData=[
	{ text: "IHLG-1", value: 1, color: "red" },
	{ text: "IHLG-2", value: 2, color: "red" },
	{ text: "IHLG-3", value: 3, color: "red" },
	{ text: "IHLG-4", value: 4, color: "red" },
	{ text: "INVOIT-1", value: 5, color: "blue" },
	{ text: "V-8ER42-1", value: 6, color: "pink" },
	{ text: "V-8ER42-2", value: 7, color: "pink" },
	{ text: "V-8ER42-3", value: 8, color: "pink" },
	{ text: "V-8ER42-4", value: 9, color: "pink" },
	{ text: "V-8ER42-5", value: 10, color: "pink" },
	{ text: "V-8ER42-6", value: 11, color: "pink" },
	{ text: "V-8ER42-7", value: 12, color: "pink" },
	{ text: "DL3360-1", value: 13, color: "yellow" },
	{ text: "DL3360-2", value: 14, color: "yellow" },
	{ text: "DL3360-3", value: 15, color: "yellow" },
	{ text: "DL3360-4", value: 16, color: "yellow" },
	{ text: "DL3360-5", value: 17, color: "yellow" },
	{ text: "DL3360-6", value: 18, color: "yellow" },
	{ text: "DL3360-7", value: 19, color: "yellow" },
	{ text: "DL3360-8", value: 20, color: "yellow" },
	{ text: "DL3360-9", value: 21, color: "yellow" },
	{ text: "DL3360-10", value: 22, color: "yellow" },
	{ text: "DL3360-11", value: 23, color: "yellow" },
	{ text: "DL3360-12", value: 24, color: "yellow" },
	{ text: "DL3360-13", value: 25, color: "yellow" },
	{ text: "DL3360-14", value: 26, color: "yellow" },
	{ text: "I3P572-1", value: 27, color: "green" },
	{ text: "I3P572-2", value: 28, color: "green" },
	{ text: "I3P572-3", value: 29, color: "green" },
	{ text: "I3P572-4", value: 30, color: "green" },
	{ text: "I3P572-5", value: 31, color: "green" }
]

var colorList = ['red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red',
				'blue', 'blue', 'blue', 'blue', 'blue', 'blue', 'blue', 'blue', 'blue', 'blue',
				'gray', 'gray', 'gray', 'gray', 'gray', 'gray', 'gray', 'gray', 'gray', 'gray',
				'pink', 'pink', 'pink', 'pink', 'pink', 'pink', 'pink', 'pink', 'pink', 'pink']
